### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Coridane** [Coridane/prework-study-guide#1]
# HTML

## User Story
As a boot camp student,
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Yash8840** [comment]
Hey Coridane, I want to contribute to your project, please assign it to me, also, can you tell me that in what form do you want the notes to appear?
